### ISSUE TITLE
Jool Altitude

### ISSUE THREAD

**Issue by Mireru** [BobPalmer/Karbonite#106]
Jool's atmosphere ends at around 139km.  The game however (legacy?) considers anything under 200km as sub-orbital.  As such, to harvest from Jool using a Particle Collector, you'd need to be in a sub-orbital flight, which, at least for me, seems to invoke a crash at higher time-warps.

Would like to request a way to tweak the numbers for the orbital altitude for the collectors, at least for Jool.  (Really would rather Squad fix Jool but meh)

**Comment by BobPalmer** [comment]
(Confirm this is fixed)

**Comment by BobPalmer** [comment]
Fixed in new CRP
