### ISSUE TITLE
KarboniteGenerator IndexOutOfRange on vessel load

### ISSUE THREAD

**Issue by dhafi** [BobPalmer/Karbonite#126]
Any ship with the Karbelectric Generator part will glitch when loaded (after initial launch). No parts other than the generator will appear.

KSP 0.25, Windows 32-bit in OpenGL mode. Mods: OKS+TAC-LS+KW+Mechjeb+FAR+EVE+B9

[LOG 17:39:19.882] [FLIGHT GLOBALS]: Switching To Vessel KarboMiner DUX-1 ---------------------- 
[LOG 17:39:19.882] setting new dominant body: Kerbin
FlightGlobals.mainBody: Kerbin
[LOG 17:39:19.884] Clouds: Volume Destroyed
[LOG 17:39:19.885] Clouds: Volume Destroyed
[LOG 17:39:19.887] Clouds: Volume Destroyed
[LOG 17:39:19.917] Clouds: Volume Initialized
[LOG 17:39:19.917] Clouds: Volume Enabled=True
[LOG 17:39:19.946] Clouds: Volume Initialized
[LOG 17:39:19.947] Clouds: Volume Enabled=True
[LOG 17:39:19.976] Clouds: Volume Initialized
[LOG 17:39:19.977] Clouds: Volume Enabled=True
[EXC 17:39:19.983] IndexOutOfRangeException: Array index is out of range.
	Karbonite.KarboniteGenerator.get_StartAnimation ()
	Karbonite.KarboniteGenerator.PlayStartAnimation (Int32 speed)
	Karbonite.KarboniteGenerator.CheckAnimationState ()
	Karbonite.KarboniteGenerator.OnLoad (.ConfigNode node)
	PartModule.Load (.ConfigNode node)
	Part.LoadModule (.ConfigNode node, System.Int32& moduleIndex)
	ProtoPartModuleSnapshot.Load (.Part hostPart, System.Int32& moduleIndex)
	ProtoPartSnapshot.Load (.Vessel vesselRef, Boolean loadAsRootPart)
	ProtoVessel.LoadObjects ()
	Vessel.Load ()
	Vessel.MakeActive ()
	FlightGlobals.setActiveVessel (.Vessel v, Boolean force)
	FlightGlobals.SetActiveVessel (.Vessel v)
	FlightDriver.Start ()
[LOG 17:39:19.997] SmokeScreenConfig could not load config
[EXC 17:39:20.001] NullReferenceException: Object reference not set to an instance of an object
	Part.ModulesOnStart ()
	Part+
.MoveNext ()
[LOG 17:39:20.057] [KAE] Registering field prefabs for version 1.7.1.2 (latest)

**Comment by BobPalmer** [comment]
This module has been deprecated.
