### ISSUE TITLE
Karbonite -> liquid hydrogen

### ISSUE THREAD

**Issue by 0x03BB** [BobPalmer/Karbonite#128]
Could we get a liquid hydrogen option on the Karbonite Converters? Since it can be made into Liquid Fuel (or Kerosene) it's gotta have hydrogen in it.

I currently have the following module loaded into the 2.5 m converter with Module Manager:
```
MODULE
{
	 name = USI_Converter
	 converterName = Liquid Hydrogen
	 conversionRate = 1
	 inputResources = ElectricCharge, 3, Karbonite, 1
	 outputResources = LiquidHydrogen,4.6,False
}
```
I tried to pick values that conformed with the rest of the mod. It uses the same amount of electricity per second as the LFO converter. It fills up a hydrogen tank from Near Future in about the same amount of time as an LFO tank of the same volume would be by the LFO option (although hydrogen is so light you need bigger tanks of it, so it might be better to put the output higher). And it results in more mass being thrown away in the conversion process than with LFO, which I figure makes sense since you're only taking the hydrogen out of the Karbonite.

**Comment by BobPalmer** [comment]
Already in
