### ISSUE TITLE
KAC (Kerbal Alarm Clock) integration, like KCT (Kerbal Construction Time) did.

### ISSUE THREAD

**Issue by Climberfx** [BobPalmer/Karbonite#129]
Hello RoverDude. I was talking about the possibility of having an alarm set when the karbonite vessel have full of resources in background, and let Kerbal Alarm Clock know it by sending him the trigger. I told first to TriggerAu, creator of KAC, and he told that your mod could use the KAC API to create alarms as Karbonite plugin will have all the details about fill time/rates, etc. This is exactly what KCT does for construction times. (for example)
Is just an idea, to help users know what is the right time to focus back the vessel to transport the resources to a space station, or sort things like that.
What you think about?

**Comment by enceos** [comment]
Amazing idea. I myself have to Alt+Tab to calculate this time manually.
