### ISSUE TITLE
On from launch/always on flag for USI_Converter module

### ISSUE THREAD

**Issue by RichardDastardly** [BobPalmer/Karbonite#130]
Not an issue so much as a small request:

* Flag in module definition to set a converter to be on at vehicle launch
* Optionally remove the toggle ( and the label ) from the rightclick menu for the involved part

I've been using the converter as a fuel mixing intake for engines - there's no need to turn it off ever, and turning it on at launch is an extra step every launch. I could probably think of a few more places it'd be useful.

Cheers.

**Comment by BobPalmer** [comment]
This exists in stock
