### ISSUE TITLE
Drills keep drilling when retracted but not properly stopped

### ISSUE THREAD

**Issue by Blackberu** [BobPalmer/Karbonite#135]
When retracting (but not stopping) drills on a ship with Karbonite tanks full (the FLT-400-based models, in my case), then emptying the Karbonite tanks completely to another ship, the drills keep working and filling the tanks, even if the ship had left the surface of the Mun days ago. 

This bug has been spotted on the latest version of Karbonite (0.5.1), in my case with the mini drill, and another ksp forum user reported the same issue with the large drill. 

Notable mods installed along Karbonite in my install: MechJeb, Kerbal Engineer, universal storage, KAS, scansat (dev version), dmagic orbital science, Mod-oriented tech tree, Module Manager, Final Frontier. All up to date. The lander used had only stock + Karbonite parts. 

If you need any further information, do not hesitate to contact me.

**Comment by BobPalmer** [comment]
Fixed with new version of Regolith
