### ISSUE TITLE
Karbonite drills

### ISSUE THREAD

**Issue by Prototype2001** [BobPalmer/Karbonite#139]
Loading to a craft or coming out of the time-warp stops the drills from working with a message saying "must land first" toggling "start karbonite drill" resumes the harvesting, otherwise no resource harvesting occurs.

**Comment by BobPalmer** [comment]
Unable to repro, confirm Regolith version please

**Comment by Prototype2001** [comment]
I installed MKS last twice, is the latest Rego version included in that?

**Comment by BobPalmer** [comment]
Closing as this should be fixed in stock
