### ISSUE TITLE
Resources not Appearing on Map

### ISSUE THREAD

**Issue by axelmagn** [BobPalmer/Karbonite#140]
I've posted this in the forum, but I thought it might belong here.  A solution would be great, but I figured at the very least I could let you know of the issue.

I'm having a problem with karbonite (or any resource) not showing up on either the map view or the SCANSAT map.  I also think some buttons are missing from the right click interface.  I've linked some screenshots to show some examples.  I realize that I'm running some additional mods that could effect it, but I figured this was the best place to post it since it involves the Karbonite resource.

http://imgur.com/a/VcNOt

Please let me know if I can supply any additional info.

**Comment by BobPalmer** [comment]
Looks like an install issue - assume this was sorted on the forums
