### ISSUE TITLE
Karbonite converters instantaneous conversion glitch

### ISSUE THREAD

**Issue by enceos** [BobPalmer/Karbonite#143]
For some reason my Karbonite converters and distillers convert resources instantly after pressing the corresponding button. Works with every resource: LF, O, LFO, Monoprop.

How it happens:
1. I set Karbonite for mining and come back to the mining base after several hours.
2. Right after loading when i get into a converter's rightclick menu and choose an option like "Start Oxidizer", Karbonite converts instantly into the chosen resource skipping the conversion time rates.

My output_log.txt : https://www.dropbox.com/s/sd078rklwjqisgj/output_log4.rar?dl=0

I have latest versions of Karbonite and MKS.

**VIDEO:**
[![Karbonite Converters glitch](http://img.youtube.com/vi/LcT_lNeufww/0.jpg)](http://www.youtube.com/watch?v=LcT_lNeufww)

**Comment by BobPalmer** [comment]
Fixed this in the next update :)

**Comment by M3tal-Warrior** [comment]
Same is with the Generator - it also never really switches off after being started once (handle on green, glowing insides despite being off). First start everything is normal (takes 10 seconds to process 10 karbonite), after a stop all is processed instantly.

**Comment by BobPalmer** [comment]
Closing as this should be resolved in stock
