### ISSUE TITLE
Spurious interplanetary karbonite readings

### ISSUE THREAD

**Issue by Entropy2016** [BobPalmer/Karbonite#147]
I think I've found spurious Interplanetary Karbonite readings.

Here's some screenshots:  http://imgur.com/a/jV5DX

And between all those altitudes there's a concentration level of zero.  It's my understanding that there'd be  (at most) only one band of karbonite per celestial body, and yet at very different altitudes the sensor claims there's some there.  And taking a particle collector to any of those altitudes yielded nothing.

I found these readings during timewarp of an eccentric orbit through all those altitudes.    Attempts to use HyperEdit to put me exactly back into a circular orbit at any of those altitudes fails to reproduce a non-zero concentration.  So I'm assuming this is a bug.

**Comment by Voltara** [comment]
Looking over the Regolith code, it seems altitude banding is broken for Interplanetary karbonite (I put in a ticket for that at https://github.com/BobPalmer/Regolith/issues/26).

So at least as of the current version, altitude should not be a factor at all.  Outside of Kerbin and Jool, there is only a 20% chance to find Interplanetary karbonite.  If I'm reading this code right, the presence and concentrations are rolled on a per-biome basis.  Notice all of your screenshots were above "Highlands" - my guess is HyperEdit put you in a different biome?

**Comment by Entropy2016** [comment]
I'm not familiar with the code so I'll take your word about that mistake your'e alluding to… but yeah, you're spot on about the signal correlating with the Highlands biome.  I just gave it another go and watched in real time and every time I went into the Highlands I got an interplanetary karbonite signal.  I confirmed the same effect with a particle collector (as opposed to the karbonite scanner).

**Comment by MrKiel** [comment]
I'd like to backup Voltara here - I'm also seeing Interplanetary Karbonite unaffected by altitude; My current career save has generated a Karbonite band around the Sun but the Advanced Particle Collector will collect the same amount of Karbonite at *any* altitude above the Sun - meaning Karbonite is available pretty much anywhere in the Solar System :\

**Comment by Entropy2016** [comment]
Hmm, the Regolith issue Voltara linked to appears to be closed, and Regolith 0.1.6 was released with a changelog mentioning "Fixed bug with exospheric resources", but even with the Regolith 0.1.6 I still see interplanetary karbonite correlating with the biome I'm flying over rather than it correlating with altitude.  Were these actually separate bugs with interplanetary karbonite?

**Comment by thor79** [comment]
Entropy, I would say yes, they were separate bugs. I'm seeing interplanetary karbonite attached to the biome I'm flying over with Regolith 0.1.7. On Kerbin, I'm seeing interplanetary Karbonite over Tundra, Shores, Deserts, Badland, and Highlands, but not the rest of the Biomes.

**Comment by BobPalmer** [comment]
Should be fixed in stock
