### ISSUE TITLE
Inline Landing Gear Kraken

### ISSUE THREAD

**Issue by Donziboy2** [BobPalmer/Karbonite#152]
The inline landing gear has a small baby kraken that will wait until you least expect it to emerge and tear the top half of your craft off.  Generally it occurs on landed craft, a craft I had used several times (been there for 2 kerbal years) on the Mun tore itself apart this morning when I did a quick 10x time warp.  I have had this in the past and most recently it has occurred and reminded me why I stopped using that part on craft.

Pic of the gear from thread.
http://i.imgur.com/OZu0yZu.png

**Comment by BobPalmer** [comment]
Note to self - consider switching to box colliders

**Comment by Starwaster** [comment]
Bob, have you assigned breakingForce / breakingTorque values to that part? If not, the default values might be too weak. I've seen stock LVN engine fall off just floating in space because of it.

**Comment by BobPalmer** [comment]
I'll take a look :)
