### ISSUE TITLE
SRBs ignore thrust limiting

### ISSUE THREAD

**Issue by LPGhatguy** [BobPalmer/Karbonite#158]
Presently, the RAT Karbonite SRBs ignore the thrust limit set in the VAB.

This can be tested by creating a craft with just a RAT SRB, and setting the thrust limit to low enough that KER will report the craft's TWR as being less than 1. Upon launching, the craft will still lift off (and KER will report a much higher TWR).

This makes sense given what the SRBs are, but is inconsistent with the rest of the game's SRBs.

**Comment by Khalkion** [comment]
Somehow it's connected with USI_WiggleEngine module. It modifies thrust when the speed of vessel is changed.
