### ISSUE TITLE
LSX and LS-40 missing node_attach

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [BobPalmer/Karbonite#173]
They don't have one defined, so when surface-attaching, their geometric center is used as the attach point, leaving them stuck halfway into the parent part.  Should they have surface attachment at all, or should the attachment point be at their top (i.e. the same as node_stack_top), or somewhere on the side?

**Comment by BobPalmer** [comment]
These are not meant to be surface attach and are node attach only.
