### ISSUE TITLE
Bottom node for ke_625 engine glitched

### ISSUE THREAD

**Issue by xellas84** [BobPalmer/Karbonite#178]
Node will not allow proper attachment.  Items will appear to attach, but then it appears to attach to the TOP of the node rather than the bottom, and the game attempts to force the stack to go back up rather than down.

Temporary fix I am using is to change node_stack_bottom from "0.0, 0.01, 0.0, 0.0, 1.0, 0.0, 0" to "0.0, 0.01, 0.0, 0.0, -1.0, 0.0, 0"  This appears to resolve the issue.

**Comment by Neouni** [comment]
Yes that fixes it for KA_Engine_625_01

Did a quick search through the mod for similar issues.

The SRB's: KA_SRB_125_01, KA_SRB_125_02, KA_SRB_625_01, KA_SRB_625_01
also have a flipped Y attach value from pre 1.0

Not sure KA_Drill_Radial_04 needs a definition of it
