### ISSUE TITLE
When you take the Medium ducted fan out of editor inventory, it spams the output log with an exception.

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/Karbonite#184]
I only saw this one because I was looking at a different exception.

Just drag the medium ducted fan out of the editor partlist and it'll spam the log with this exception:
MissingFieldException: Field '.Vessel.staticPressure' not found.

Output log: http://sta.sh/0w5jsx44r6o

**Comment by Kerbas-ad-astra** [comment]
That problem is caused by having an out-of-date ModuleRCSFX.  FTT comes bundled with an out-of-date version, so you'll want to go to [the repo for that addon](https://github.com/NathanKell/ModuleRCSFX/releases) and get the latest release.

**Comment by smjjames** [comment]
Oh I see, thanks.
