### ISSUE TITLE
Karbonite no longer has variation in biomes, while everything else does

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/Karbonite#185]
Basically, Karbonite will have the exact same percentage over an entire biome while every other resource (including Ore) will vary in their abundance, For example, there will be 1.25 here in Biome A and 1.47 in another spot in Biome A, Karbonite doesn't do this.

**Comment by futrtrubl** [comment]
Are you looking at Kerbin? I believe Kerbin is specified that way for testing purposes.

**Comment by smjjames** [comment]
Nope, Moho, also checked Minmus. Along with other bodies in the system, even with biome lock off.

Not sure if me using SCANsat dev version 13.2 has anything to do with it though. Since the other resources have regional variance, I figured it was a Karbonite problem.
