### ISSUE TITLE
KSP not loading after installation of Karbonite

### ISSUE THREAD

**Issue by rubdos** [BobPalmer/Karbonite#188]
Hi!

I'm going to do several things wrong in this issue report, but tell me what info you need and I'll supply it.

I have several mods installed using CKAN:
- CC_RemoteTech autodetected dll
- CC_SCANsat autodetected dll
- CommunityResourcePack 0.4.4
- ContractConfigurator autodetected dll
- ContractConfigurator-KerbinSpaceStation 2.2
- ContractConfigurator-RemoteTech 2.0.0
- DeadlyReentry v7.2.2
- FerramAerospaceResearch 2:v0.15.4.1_Goldstein
- FirespitterCore v7.1.4
- InfernalRobotics v0.21.3
- IR-Model-Rework-Core v01b
- IR-Model-Rework-Expansion v01b
- Karbonite 0.6.3
- KerbalAlarmClock v3.4.0.0
- KerbalEngineerRedux 1.0.18.0
- Kopernicus 1:beta-02-4
- kOS 0.17.3
- MiniAVC autodetected dll
- MissionController2 1.21
- ModularFlightIntegrator 1.1.1
- ModuleManager 2.6.7
- OuterPlanetsMod 1:1.7.2
- PlanetShine 0.2.3.1
- PlanetShine-Config-Default 0.2.3.1
- ProceduralFairings v3.15
- ProceduralFairings-ForEverything v0.0.3
- ProceduralParts v1.1.7
- RemoteTech v1.6.7
- SCANsat v14.1
- ScienceAlert 1.8.9
- SpaceY-Lifters 1.0.0
- Toolbar 1.7.9
- TransferWindowPlanner v1.3.1.0
- TweakScale v2.2.1
- UKS 0.31.6
- USI-LS 0.1.5
- USITools 0.4.2

When installing Karbonite via ckan (`ckan install Karbonite`), KSP refuses to launch. The current Karbonite version in ckan is 0.6.3.

KSP seems to get stuck on loading `KA_Engine_125_01`.

![screenshot from 2015-08-18 11-32-14](https://cloud.githubusercontent.com/assets/1263440/9326813/dee14c66-459c-11e5-9c04-3046054c7b96.png)

What logs/files/info/... do you need from me to debug? Should I whether a clean install solves the issue?

I'm running Linux 64 bit (Fedora 22), if that matters. KSP 1.0.4

**Comment by ArnePeirs** [comment]
Logs are always helpfull

**Comment by rubdos** [comment]
This part (last part of the log) seems interesting:

> [LOG 10:39:17.961] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Analyzer/KA_Analyzer_01'
> [LOG 10:39:18.022] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Analyzer/KA_Analyzer_01' has no database record. Creating.
> [LOG 10:39:18.048] DragCubeSystem: Creating drag cubes for part 'KA.Analyzer.01'
> [LOG 10:39:18.112] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_AtmScoop_125_01/KA_AtmScoop_125_01'
> [ERR 10:39:18.122] [ShipTemplate]: No Resource definition found for RESOURCE
> 
> [WRN 10:39:18.166] Could not create PartResource of type 'IntakeAtm
> [LOG 10:39:18.228] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_AtmScoop_125_01/KA_AtmScoop_125_01' has no database record. Creating.
> [LOG 10:39:18.265] DragCubeSystem: Creating drag cubes for part 'KA.AtmScoop.125.01'
> [LOG 10:39:18.342] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_AtmScoop_250_01/KA_AtmScoop_250_01'
> [ERR 10:39:18.352] [ShipTemplate]: No Resource definition found for RESOURCE
> 
> [WRN 10:39:18.381] Could not create PartResource of type 'IntakeAtm
> [LOG 10:39:18.418] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_AtmScoop_250_01/KA_AtmScoop_250_01' has no database record. Creating.
> [LOG 10:39:18.448] DragCubeSystem: Creating drag cubes for part 'KA.AtmScoop.250.01'
> [LOG 10:39:18.531] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Converter_125_02/KA_Converter_125_01'
> [LOG 10:39:18.632] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Converter_125_02/KA_Converter_125_01' has no database record. Creating.
> [LOG 10:39:18.658] DragCubeSystem: Creating drag cubes for part 'KA.Converter.125.01'
> [LOG 10:39:18.729] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Converter_250_01/KA_Converter_250_01'
> [LOG 10:39:18.805] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Converter_250_01/KA_Converter_250_01' has no database record. Creating.
> [LOG 10:39:18.834] DragCubeSystem: Creating drag cubes for part 'KA.Converter.250.01'
> [LOG 10:39:18.894] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_DetectionArray_01/KA_DetectionArray_01'
> [LOG 10:39:19.033] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_DetectionArray_01/KA_DetectionArray_01' has no database record. Creating.
> [LOG 10:39:19.053] DragCubeSystem: Creating drag cubes for part 'KA.DetectionArray.01'
> [LOG 10:39:19.109] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Distiller_125_01/KA_Distiller_125_01'
> [LOG 10:39:19.208] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Distiller_125_01/KA_Distiller_125_01' has no database record. Creating.
> [LOG 10:39:19.233] DragCubeSystem: Creating drag cubes for part 'KA.Distiller.125.01'
> [LOG 10:39:19.289] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Distiller_250_01/KA_Distiller_250_01'
> [LOG 10:39:19.358] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Distiller_250_01/KA_Distiller_250_01' has no database record. Creating.
> [LOG 10:39:19.380] DragCubeSystem: Creating drag cubes for part 'KA.Distiller.250.01'
> [LOG 10:39:19.426] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Drill_125_01/KA_Drill_125_01'
> [LOG 10:39:19.476] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Drill_125_01/KA_Drill_125_01' has no database record. Creating.
> [LOG 10:39:19.494] DragCubeSystem: Creating drag cubes for part 'KA.Drill.125.01'
> [LOG 10:39:19.518] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Drill_250_01/KA_Drill_250_01'
> [LOG 10:39:19.648] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Drill_250_01/KA_Drill_250_01' has no database record. Creating.
> [LOG 10:39:19.718] DragCubeSystem: Creating drag cubes for part 'KA.Drill.250.01'
> [LOG 10:39:19.765] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Drill_Radial_01/KA_Drill_Radial_01'
> [LOG 10:39:19.812] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Drill_Radial_01/KA_Drill_Radial_01' has no database record. Creating.
> [LOG 10:39:19.826] DragCubeSystem: Creating drag cubes for part 'KA.Drill.Radial.01'
> [LOG 10:39:19.848] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Drill_Radial_04/KA_Drill_Radial_04'
> [LOG 10:39:19.892] PartLoader: Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Drill_Radial_04/KA_Drill_Radial_04' has no database record. Creating.
> [LOG 10:39:19.906] DragCubeSystem: Creating drag cubes for part 'KA.Drill.Radial.04'
> [LOG 10:39:19.950] PartLoader: Compiling Part 'UmbraSpaceIndustries/Karbonite/Parts/KA_Engine_125_01/KA_Engine_125_01'
> [LOG 10:39:19.958] Added sound_rocket_hard to FXGroup running
> [LOG 10:39:19.959] Added sound_explosion_low to FXGroup flameout
> [LOG 10:39:19.962] Karbonite not found in resource database. Propellant Setup has failed.
> [EXC 10:39:19.963] NullReferenceException: Object reference not set to an instance of an object
> 	ModuleEngines.SetupPropellant ()
> 	ModuleEngines.OnLoad (.ConfigNode node)
> 	PartModule.Load (.ConfigNode node)
> 	Part.AddModule (.ConfigNode node)
> 	PartLoader.ParsePart (.UrlConfig urlConfig, .ConfigNode node)
> 	PartLoader+.MoveNext ()
> [EXC 10:39:19.971] NullReferenceException: Object reference not set to an instance of an object
> 	PartLoader.GetDatabaseConfig (.Part p)
> 	PartLoader.GetDatabaseConfig (.Part p, System.String nodeName)
> 	DragCubeSystem.LoadDragCubes (.Part p)
> 	Part+.MoveNext ()
> [LOG 10:52:36.804] RemoteTech: ModuleSPU: OnDestroy
> [LOG 10:52:36.804] RemoteTech: ModuleRTAntennaPassive: OnDestroy

**Comment by Kerbas-ad-astra** [comment]
Are you sure you have Community Resource Pack installed (or installed properly)?  That should give KSP the Karbonite and IntakeAtm resources, but the log says it can't find them.

**Comment by rubdos** [comment]
It wasn't installed. I thought ckan would pull dependencies in?

Anyhow, I installed CommunityResourcePack (ckan install) and that didn't fix it. The weird log entries have gone, no real errors appear to me. I will probably reinstall the whole KSP directory after the exams and I'll come back to this issue, to see whether it resolved itself.

**Comment by BobPalmer** [comment]
Closing
