### ISSUE TITLE
MFT configuration needs utilization parameter

### ISSUE THREAD

**Issue by mhoram-kerbin** [BobPalmer/Karbonite#191]
Details are here:
http://forum.kerbalspaceprogram.com/threads/89401-1-0-4-Karbonite-Mineable-Burnable-and-Community-Driven-0-6-4-2015-08-24?p=2163513&viewfull=1#post2163513

**Comment by silviu609** [comment]
https://gist.github.com/silviu609/2b7aa304e46e022d3e78/archive/9a333e08fb379a6beaae8e6edfc0a07394740c23.zip

// Karbonite MFT|RF support
@TANK_DEFINITION[Default]:FOR[Karbonite]:NEEDS[modularFuelTanks|RealFuels]
{
    TANK
    {
        name = Karbonite
        amount = 0.0
        utilization = 5
        maxAmount = 0.0
    }
}
@TANK_DEFINITION[Fuselage]:FOR[Karbonite]:NEEDS[modularFuelTanks|RealFuels]
{
    TANK
    {
        name = Karbonite
        amount = 0.0
        utilization = 5
        maxAmount = 0.0
    }
}
@TANK_DEFINITION[Structural]:FOR[Karbonite]:NEEDS[modularFuelTanks|RealFuels]
{
    TANK
    {
        name = Karbonite
        amount = 0.0
        utilization = 5
        maxAmount = 0.0
    }
}
@TANK_DEFINITION[ServiceModule]:FOR[Karbonite]:NEEDS[modularFuelTanks|RealFuels]
{
    TANK
    {
        name = Karbonite
        amount = 0.0
        utilization = 5
        maxAmount = 0.0
    }
}
