### ISSUE TITLE
Radial Landing Legs collide with surface at launch

### ISSUE THREAD

**Issue by Clank1** [BobPalmer/Karbonite#200]
Whenever I have radial landing legs attached to a craft it reacts with the floor and causes the craft to shoot off rapidly, direction & speed are random each time, e.g: http://imgur.com/a/r3tkI

**Comment by Artson** [comment]
I also have this problem. It is also present if the lander legs are retracted. It happens both on the launchpad and on landings.

**Comment by KyJoCa** [comment]
I'm also having this issue with 1.1.2 and the most up-to-date versions of (pretty much all) USI mods.
