### ISSUE TITLE
Propeller engines have no sound

### ISSUE THREAD

**Issue by Smorfty** [BobPalmer/Karbonite#201]
None of the propeller engines make any sound in my game. All other engines make sound just fine.
I'm using Karbonite v0.7.0.0 on the 1.1 prerelase build 1196.
The propellers never animate either. They look like this: http://i.imgur.com/8EF6Xku.jpg whether they're turned on or not.

**Comment by BobPalmer** [comment]
You have a Firespitter issue.  If this is still an issue bring it up on the forums
