### ISSUE TITLE
AssemblyLoader: Exception loading 'Karbonite'

### ISSUE THREAD

**Issue by Jonney5** [BobPalmer/Karbonite#203]
Getting the following error in the in the log of the 1.1.1215 pre-release with Karbonite 7.1:

[ERR 11:34:06.818] AssemblyLoader: Exception loading 'Karbonite': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

Additional information about this exception:

 System.TypeLoadException: Could not load type 'Karbonite.KarboniteGenerator' from assembly 'Karbonite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<UpdateResources>d__0' from assembly 'Karbonite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by RealKolago** [comment]
I can confirm this. Win64 / [KSP Version]: 1.1.0.1230 (WindowsPlayer) (x64)

**Comment by smjjames** [comment]
Roverdude asked if I could put up a github issue as a reminder to remove the karbonite.DLL because it's obsolete, but since this already exists, I'll post here.

@Jonney5 and @RealKolago Just delete the karbonite.DLL

**Comment by BobPalmer** [comment]
Clear out your Karbonite folder, re-install.
